export const START_ALBUMS_LOADING = 'START_ALBUMS_LOADING';
export const STOP_ALBUMS_LOADING = 'STOP_ALBUMS_LOADING';
export const SET_ALBUMS = 'SET_ALBUMS';
export const SET_ALBUMS_ERROR = 'SET_ALBUMS_ERROR';
