export const START_TODOS_LOADING = 'START_ALBUMS_LOADING';
export const STOP_TODOS_LOADING = 'STOP_ALBUMS_LOADING';
export const SET_TODOS = 'SET_ALBUMS';
export const SET_TODOS_ERROR = 'SET_ALBUMS_ERROR';


